project_name: foobar
dist: dist

env:
  - CGO_ENABLED=0

builds:
  - id: foobar
    binary: foobar
    main: ./cmd/foobar
    ldflags:
      - "-s -w -X main.buildTimestamp={{ .Timestamp }} -X main.buildVersion={{ .Version }} -X main.buildRevision={{ .FullCommit }}"
    goos:
      - windows
    goarch:
      - amd64
    mod_timestamp: '{{ .CommitTimestamp }}'

changelog:
  skip: true

archives:
  - id: default
    format: binary
    allow_different_binary_count: true
    name_template: "foobar"

snapshot:
  name_template: 'dev-{{ slice .FullCommit 0 8}}'
